Cap_Study_App/Study_app/urls.py
from django.urls import  path
from . import views




app_name = 'study_app'

urlpatterns = [

    #================ Users Views ================#

    path('login/', views.login, name='login'),
    path('', views.homepage, name='homepage'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),


    #================ Projects Views ================#

    path('projects/', views.projects, name='projects'),
    path('projects/<int:project_id>', views.projdetail, name='projdetail'),
    path('delete_proj/<int:project_id>', views.delete_proj, name='delete_proj'),


     #================ Resources Views ================#

    path('resource/', views.resource, name='resource'),
    path('resources/<int:resource_id>', views.resourcedetail, name='resourcedetail'),
    path('deleteresource/<int:resource_id>', views.deleteresource, name='deleteresource'),
    path('addresources/<int:project_id>', views.addresources, name='addresources'),

    
    #================ FlashCards Views ================#

    path('flashcards/', views.flashcards, name='flashcards'),
    path('dictionary/', views.dictionary, name='dictionary')

]

Cap_Study_App/capstone_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from study_app import views 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('study_app.urls')),
   
]

Cap_Study_App/studyApp_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from Study_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Study_app.urls'))
]

Cap_Study_App/Study_app/models.py
from django.db import models
from django.contrib.auth.models import User



#=============== Projects models===============

class Project(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='projects')
    title = models.CharField(max_length=250)
    description = models.TextField(max_length=300)
    due_date = models.DateField(null=True)
    is_finished = models.BooleanField(default=False)

    def __str__(self):
        return self.title


#=============== Resources models===============
class Resource(models.Model):
    name   = models.CharField(max_length=250)
    author = models.CharField(max_length=250)
    price  = models.DecimalField(decimal_places=2, max_digits=20)
    url    = models.CharField(max_length=300)
    resources_type = models.CharField(max_length=50)
    date_published = models.DateField(null=True)
    
    # This ManyToManyField will allow many Projects, each user can create many projects.
    projects = models.ManyToManyField(Project, related_name='resources')

    def __str__(self):
        return self.name


#=============== Flash Cards models===============

class FlashCard(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='flashcards')
    question   = models.CharField(max_length=250)
    answer   = models.CharField(max_length=250)

    def __str__(self):
        return self.answer

Cap_Study_App/Study_app/views.py
from .models import Project
from django.contrib import messages
from django.contrib.auth import (authenticate, login
as django_login, logout as django_logout)
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from . form import Project, Resource, ProjectForm, ResourceForm,RegisterForm,DictionaryForm


# =============================================================================================
# Create your views here.
def register(request):
    if request.method== "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"{username} account is successfully created...")
            return redirect('study_app:login')

    else:
        form = RegisterForm()

    context = {
        'form': form
    }

    return render(request, 'layout/register.html', context)


# ===========================================================================================

def flashcards(request):
    return render(request, 'layout/flashcards.html')


# ===============================================================================================

# Login View
def login(request):
    if request.method == "POST":
        form = request.POST

        username = form.get('username')
        password = form.get('password')

        user = authenticate(request, username=username, password=password)
        if user is None:
            messages.error(request, "Invalid username or password")

            context ={
                
            }
            return render(request, 'layout/login.html', context)

        django_login(request, user)

        return redirect('study_app:homepage')


    elif request.method == "GET":
       

        context={
            
        }
        return render(request, 'layout/login.html', context)
# ===============================================================================================

@login_required
def homepage(request):
    return render(request, 'home/homepage.html')

# =============================================================================================== 

@login_required
def projects(request):
    if request.method == "POST":
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = Project(user=request.user, title=request.POST['title'], description=request.POST['description'])
            project.save()

        messages.success(request, f"The project created by {request.user.username} is successfully added....")
        return redirect('study_app:projects')

    elif request.method== "GET":
        form = ProjectForm()
    projects = Project.objects.filter(user=request.user)
    context={
        'projects': projects,
        'form':form 
    }
    return render(request, 'home/project.html', context)
# ===============================================================================================

@login_required
def profile(request):
    projects = Project.objects.filter(is_finished=False, user=request.user)
    resources = Resource.objects.filter(name=request.user)

    # homeworks = Homework.objects.filter(is_finalized=False, user=request.user)
    # if len(homeworks)== 0:
    #     homework_done = True
    # else:
    #     homework_done = False

    if len(projects)== 0:
        project_done = True
    else:
        project_done = False

    context ={
        'projects':projects,
        'project_done':project_done,
        'resources': resources,
        # 'homeworks':homeworks,
        # 'homework_done':homework_done,
    }

    return render(request, 'layout/profile.html', context)
# ===============================================================================================

def projdetail(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    context = {
        'project': project
    }
    return render(request, 'home/projdetail.html', context)

# ===============================================================================================
@login_required
def resource(request):
    if request.method == "POST":
        form = ResourceForm(request.POST)
        if form.is_valid():
            resource = Resource(name=request.POST['name'], author=request.POST['author'], price=request.POST['price'], resources_type=request.POST['resources_type'], url=request.POST['url'])
            resource.save()

        messages.success(request, f"The resource added by {request.user.username} is successful....")
        return redirect('study_app:resource')

    elif request.method== "GET":
        form = ResourceForm()
        resources = Resource.objects.filter(name=request.user)
        projects = Project.objects.filter(user=request.user)
    
        context={
            'resources': resources,
            'form':form, 
            'projects':projects
        } 
    return render(request, 'home/resource.html', context)
    

# ===============================================================================================

def resourcedetail(request, resource_id):
    resources = get_object_or_404(Resource, id=resource_id)
    context = {
        'resources': resources
    }
    return render(request, 'home/resourcedetail .html', context)
# ===================================================================================================

# fix the error when u come back form break
@login_required
def delete_proj(request, project_id):
    projects=get_object_or_404(Project, id=project_id)
    projects.delete()
    return redirect('study_app:projects')

@login_required
def deleteresource(request, resource_id):
    resources=Resource.objects.get(Resource, id=resource_id)
    resources.delete()
    return redirect('study_app:resource')

def logout(request):
    django_logout(request)
    return redirect( 'study_app:login')
# ==========================================================================================

def addresources(request, project_id):
    if request.method == "POST":
        project = Project.objects.get(id=project_id)
        form = ResourceForm(request.POST or None)
        if form.is_valid():

            new_resource = form.save()
            new_resource.projects.add(project)
           
            messages.success(request, "The resource is added successfully.....")

        return redirect('study_app:projdetail', project_id)

    else:
        project =Project.objects.get(id=project_id)
        form = ResourceForm()
        context = {
            'project': project,
            'form': form
        }
    return render(request, 'home/addresources.html', context)

# ============================================================================================

def flashcards(request):
    return render(request, 'layout/flashcards.html')

def dictionary(request):
    form = DictionaryForm()
    context= {
        'form': form
    }
    return render(request, 'home/dictionary.html', context)

Cap_Study_App/Study_app/templates/layout/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    
    <!-- BOOTSTRAP BUNDLE -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script> 

    <!-- JQUERY -->
    <script src="https://code.jquery.com/jquery-3.6.0.js"
        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

    <!-- Axios -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.27.2/axios.min.js"></script>
            

    <!--BOOTSTRAP ICONS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">

    <!-- NORMALIZE CSS -->
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">

    <link rel="stylesheet" href="{% static 'css/index.css' %}">

    <title>Capstone_Study-App</title>
</head>
<body>
    {% include 'layout/navbar.html' %}
    <div class="container">

        {% if messages %}
            {% for message in messages %}
                <h4 class="text-center mt-3">
                    {{message}}
                </h4>
            {% endfor %}
        {% endif %}



        {% block content %}

        {% endblock content %}

    </div>
</body>

</html>

Cap_Study_App/Study_app/templates/layout/flashcards.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/flashjs.css' %}">
    <title>FlashCard Game</title>
</head>

<body id="body">
    <div class="d-flex justify-content-center flex-column gap-5">
        <div class="container d-flex justify-content-center mb-5">
            <div id="flash" class="flash">
                Let Play FlashCard Game!
            </div>
        </div>
        <div class="container">
            <h1>Question</h1>
            <div class="control">
                <button id="start-btn" class="start-btn btn">Start</button>
            </div>
            <div id="question-container" class="hide">
                <div id="question">Question</div>
                <div id="show-answer" class="btn-grid">
                    <button id="show-ans" class="show-ans btn-1">Show Answer</button>
                </div>
                <div id="post-response" class="hide">
                    <div class="show-answer">
                        Did you get right?
                    </div>
                    <div id="answer-buttons" class="btn-grid">
                        <button id="yes" class="btn">Yes</button>
                        <button id="no" class="btn">No</button>
                    </div>
                </div>
                <div id="next-question" class="hide">
                    <button id="next-btn" class="next-btn btn">Next</button>
                </div>
            </div>
        </div>
        <div class="score" id="game">
            <h1 class="h1">Score</h1>
            <p class="score-text" id="score">0</p>
        </div>
    </div>

    <script src="{% static 'js/flashcards.js' %}"></script>
</body>

</html>

Cap_Study_App/Study_app/templates/layout/login.html
{% extends 'layout/base.html' %}

{% block content %}


<h1 class="h1 text-center m-5">LOG IN</h1>
<form action="{% url 'study_app:login' %}" method="POST" class="row g-3 offset-4 d-flex flex-column align-item-center">

    <div class="col-md-6">
        <label for="username" class="form-label"><h2>Username</h2></label>
        <input type="text" name="username" class="form-control" id="username">   
    </div>

    <div class="col-md-6">
        <label for="password" class="form-label"><h2>Password</h2></label>
        <input type="password" name="password" class="form-control" id="password">
    </div>

    {% csrf_token %}
    <div class="col-lg-6 text-center">
        <button class="btn-1 btn-success" style="--clr:#00ffff" type="submit"><span>LOGIN</span><i></i></button>  
    </div>
</form>

<!-- link to register route -->
<div class="col-4 offset-4 align-item-center mt-3">
    <h5>New Student Register here? <a href="{% url 'study_app:register' %}"
            class="text-decoration-none link-danger">Create Account</a></h5>
</div>

{% endblock content %}

Cap_Study_App/Study_app/templates/layout/logout.html
{% extends 'layout/base.html' %}
{% load static %}
{% block content %}
<div class="border-top pt-3 text-center">
    <h6>Your logout is successful</h6>
    <small class="text-muted">

        <a class="btn btn-danger" href="{% url 'study_app:login' %}">Login Again</a>

    </small>
</div>

{% endblock content %}

Cap_Study_App/Study_app/templates/layout/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'study_app:homepage' %}">Students Study App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
            <ul class="navbar-nav mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'study_app:homepage' %}">Home</a>
                </li>

                {% if request.user.is_authenticated %}

                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'study_app:profile' %}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'study_app:logout' %}">Logout</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Options
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'study_app:resource' %}">Resources</a></li>
                        <li><a class="dropdown-item" href="{% url 'study_app:dictionary' %}">Dictionary</a></li>
                        <li><a class="dropdown-item" href="#">Homework</a></li>
                        <li><a class="dropdown-item" href="{% url 'study_app:projects' %}">Projects</a></li>
                        <li><a class="dropdown-item" href="#">Media/Videos</a></li>
                        <li><a class="dropdown-item" href="#">Wikipedia</a></li>
                        <li><a class="dropdown-item" href="{% url 'study_app:flashcards' %}">Flash Cards</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                {% else %}

                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'study_app:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'study_app:register' %}">Register</a>
                </li>

                {% endif %}
            </ul>
        </div>
    </div>
</nav>

Cap_Study_App/Study_app/templates/layout/profile.html
{% extends 'layout/base.html' %}
{% load static %}
{% block content %}

<div class="text-center pb-2">

    <div class="container">
        {% if not project_done %}
        <h2 class="text-center">Projects</h2>
        <table class="table table-striped table-border table-hover table-dark">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Subject</th>
                    <th scope="col">Description</th>
                    <th scope="col">Due Date</th>
                    <th scope="col">Status</th>
                    <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for project in projects %}

                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <th>{{project.title}}</th>
                    <th>{{project.description}}</th>
                    <th>{{project.due_date}}</th>
                    <td>
                        <a href="#">
                            <div class="form-check">

                                <input class="form-check-input" type="checkbox" value="" 
                                {% if project.is_finished %}
                                    checked 
                                {% endif %}>

                                <label class="form-check-label text-light" for="flex-column">
                                    Mark as Completed
                                </label>
                            </div>
                        </a>
                    </td>
                    <td><a href="{% url 'study_app:delete_proj' project.id %}">
                        <i class="bi bi-trash3-fill"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}

        <h3>All projects are completed</h3>

        {% endif %}

        <a href="{% url 'study_app:projects'  %}" class="btn btn-danger">Project</a>
        <br><br>

{% endblock content %}

Cap_Study_App/Study_app/templates/layout/register.html
{% extends 'layout/base.html' %}
{% load static %}
{% block content %}


<h1 class="text-center">REGISTER</h1>
<form action="{% url 'study_app:register' %}" method="POST" class="col-4 offset-4 d-flex flex-column align-item-center">
    {{form}}
   
    {% csrf_token %}
    <button class="btn-2 btn-danger mt-4" style="--clr:#ff1867" type="submit"><span>REGISTER</span><i></i></button>
</form>

<!-- Link to Sign In Route -->
<div class="col-4 offset-4 align-item-center mt-3">
    <h5>Have an account? <a href="{% url 'study_app:login' %}" class="text-decoration-none link-danger">Sign In</a>
    </h5>
</div>

{% endblock content %}