Cap_Study_App/Study_app/urls.py
from django.urls import  path
from . import views




app_name = 'study_app'

urlpatterns = [

    #================ Users Views ================#

    path('login/', views.login, name='login'),
    path('', views.homepage, name='homepage'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),


    #================ Projects Views ================#

    path('projects/', views.projects, name='projects'),
    path('projects/<int:project_id>', views.projdetail, name='projdetail'),
    path('delete_proj/<int:project_id>', views.delete_proj, name='delete_proj'),


     #================ Resources Views ================#

    path('resource/', views.resource, name='resource'),
    path('resources/<int:resource_id>', views.resourcedetail, name='resourcedetail'),
    path('deleteresource/<int:resource_id>', views.deleteresource, name='deleteresource'),
    path('addresources/<int:project_id>', views.addresources, name='addresources'),

    
    #================ FlashCards Views ================#

    path('flashcards/', views.flashcards, name='flashcards'),
    path('dictionary/', views.dictionary, name='dictionary')

]

Cap_Study_App/capstone_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from study_app import views 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('study_app.urls')),
   
]

Cap_Study_App/studyApp_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from Study_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Study_app.urls'))
]

Cap_Study_App/Study_app/models.py
from django.db import models
from django.contrib.auth.models import User



#=============== Projects models===============

class Project(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='projects')
    title = models.CharField(max_length=250)
    description = models.TextField(max_length=300)
    due_date = models.DateField(null=True)
    is_finished = models.BooleanField(default=False)

    def __str__(self):
        return self.title


#=============== Resources models===============
class Resource(models.Model):
    name   = models.CharField(max_length=250)
    author = models.CharField(max_length=250)
    price  = models.DecimalField(decimal_places=2, max_digits=20)
    url    = models.CharField(max_length=300)
    resources_type = models.CharField(max_length=50)
    date_published = models.DateField(null=True)
    
    # This ManyToManyField will allow many Projects, each user can create many projects.
    projects = models.ManyToManyField(Project, related_name='resources')

    def __str__(self):
        return self.name


#=============== Flash Cards models===============

class FlashCard(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='flashcards')
    question   = models.CharField(max_length=250)
    answer   = models.CharField(max_length=250)

    def __str__(self):
        return self.answer

Cap_Study_App/Study_app/views.py
from .models import Project
from django.contrib import messages
from django.contrib.auth import (authenticate, login
as django_login, logout as django_logout)
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from . form import Project, Resource, ProjectForm, ResourceForm,RegisterForm,DictionaryForm


# =============================================================================================
# Create your views here.
def register(request):
    if request.method== "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"{username} account is successfully created...")
            return redirect('study_app:login')

    else:
        form = RegisterForm()

    context = {
        'form': form
    }

    return render(request, 'layout/register.html', context)


# ===========================================================================================

def flashcards(request):
    return render(request, 'layout/flashcards.html')


# ===============================================================================================

# Login View
def login(request):
    if request.method == "POST":
        form = request.POST

        username = form.get('username')
        password = form.get('password')

        user = authenticate(request, username=username, password=password)
        if user is None:
            messages.error(request, "Invalid username or password")

            context ={
                
            }
            return render(request, 'layout/login.html', context)

        django_login(request, user)

        return redirect('study_app:homepage')


    elif request.method == "GET":
       

        context={
            
        }
        return render(request, 'layout/login.html', context)
# ===============================================================================================

@login_required
def homepage(request):
    return render(request, 'home/homepage.html')

# =============================================================================================== 

@login_required
def projects(request):
    if request.method == "POST":
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = Project(user=request.user, title=request.POST['title'], description=request.POST['description'])
            project.save()

        messages.success(request, f"The project created by {request.user.username} is successfully added....")
        return redirect('study_app:projects')

    elif request.method== "GET":
        form = ProjectForm()
    projects = Project.objects.filter(user=request.user)
    context={
        'projects': projects,
        'form':form 
    }
    return render(request, 'home/project.html', context)
# ===============================================================================================

@login_required
def profile(request):
    projects = Project.objects.filter(is_finished=False, user=request.user)
    resources = Resource.objects.filter(name=request.user)

    # homeworks = Homework.objects.filter(is_finalized=False, user=request.user)
    # if len(homeworks)== 0:
    #     homework_done = True
    # else:
    #     homework_done = False

    if len(projects)== 0:
        project_done = True
    else:
        project_done = False

    context ={
        'projects':projects,
        'project_done':project_done,
        'resources': resources,
        # 'homeworks':homeworks,
        # 'homework_done':homework_done,
    }

    return render(request, 'layout/profile.html', context)
# ===============================================================================================

def projdetail(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    context = {
        'project': project
    }
    return render(request, 'home/projdetail.html', context)

# ===============================================================================================
@login_required
def resource(request):
    if request.method == "POST":
        form = ResourceForm(request.POST)
        if form.is_valid():
            resource = Resource(name=request.POST['name'], author=request.POST['author'], price=request.POST['price'], resources_type=request.POST['resources_type'], url=request.POST['url'])
            resource.save()

        messages.success(request, f"The resource added by {request.user.username} is successful....")
        return redirect('study_app:resource')

    elif request.method== "GET":
        form = ResourceForm()
        resources = Resource.objects.filter(name=request.user)
        projects = Project.objects.filter(user=request.user)
    
        context={
            'resources': resources,
            'form':form, 
            'projects':projects
        } 
    return render(request, 'home/resource.html', context)
    

# ===============================================================================================

def resourcedetail(request, resource_id):
    resources = get_object_or_404(Resource, id=resource_id)
    context = {
        'resources': resources
    }
    return render(request, 'home/resourcedetail .html', context)
# ===================================================================================================

# fix the error when u come back form break
@login_required
def delete_proj(request, project_id):
    projects=get_object_or_404(Project, id=project_id)
    projects.delete()
    return redirect('study_app:projects')

@login_required
def deleteresource(request, resource_id):
    resources=Resource.objects.get(Resource, id=resource_id)
    resources.delete()
    return redirect('study_app:resource')

def logout(request):
    django_logout(request)
    return redirect( 'study_app:login')
# ==========================================================================================

def addresources(request, project_id):
    if request.method == "POST":
        project = Project.objects.get(id=project_id)
        form = ResourceForm(request.POST or None)
        if form.is_valid():

            new_resource = form.save()
            new_resource.projects.add(project)
           
            messages.success(request, "The resource is added successfully.....")

        return redirect('study_app:projdetail', project_id)

    else:
        project =Project.objects.get(id=project_id)
        form = ResourceForm()
        context = {
            'project': project,
            'form': form
        }
    return render(request, 'home/addresources.html', context)

# ============================================================================================

def flashcards(request):
    return render(request, 'layout/flashcards.html')

def dictionary(request):
    form = DictionaryForm()
    context= {
        'form': form
    }
    return render(request, 'home/dictionary.html', context)

Cap_Study_App/Study_app/templates/home/addresources.html
{% extends 'layout/base.html' %}

{% load static %}

{% block content %}
<div class="resources">
    <h2 class="text-center mt-5">ADD RESOURCES</h2>

    <form action="{% url 'study_app:addresources' project.id %}" method="POST">
        <label for="addresource">Resources</label>
       {{form}}

        {% csrf_token %}
        <input class="btn btn-danger mt-4" type="submit">
    </form>
</div>
{% endblock content %}

Cap_Study_App/Study_app/templates/home/dictionary.html
{% extends 'layout/base.html' %}
{% load static %}


{% block content %}
<div class="container text-center">
    <h2>Dictionary</h2>
    <p>Find words pronunciations and their meanings</p>
    <form action="" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" class="btn btn-danger" value="Submit">
    </form><br>
    <div class="content-section p-0 mt-5">
        <div class="custom-header">
            <h2>input</h2>
            <h5>phonetics</h5>
            <audio id="player" src=""></audio>
            <div><i class="bi bi-volume-up-fill"></i></div>
        </div>
        <hr class="p-0 m-0">
        <p class="float-left">
            
            <h4>Definition: definition</h4>
            <h4>Example: example</h4>
        </p>
        Synonyms:
        <hr>
    </div>
</div>
    
{% endblock content %}

Cap_Study_App/Study_app/templates/home/flashcards.html
{% extends 'layout/base.html' %}

{% load static %}



{% block content %}

<!-- Linking the external js files here -->
<script src=""></script>

{% endblock content %}

Cap_Study_App/Study_app/templates/home/homepage.html
{% extends 'layout/base.html' %}
{% load static %}


{% block content %}

<div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        <div class="col-md-3">
            <a class="card-link text-decoration-none text-dark" href ="{% url 'study_app:projects' %}">
                <div class="card mt-4">
                    <img src="{% static 'images/a.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h3 class="card-title">Project</h3>
                        <p class="card-text">
                            This is a longer card with supporting text
                            below as a natural lead-in to additional
                            content. This content is a little bit longer.
                            lead-in to additional little bit longer.
                            content. This content. 
                        </p>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-3">
            <a class="card-link text-decoration-none text-dark" href ="{% url 'study_app:resource' %}">
                <div class="card mt-4">
                    <img src="{% static 'images/p.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h3 class="card-title">Resources</h3>
                        <p class="card-text">
                            This is a longer card with supporting text
                            below as a natural  This is a longer card with supporting text
                            below as a natural 
                        </p>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-3">
            <a class="card-link text-decoration-none text-dark" href="{% url 'study_app:dictionary' %}">
                <div class="card mt-4">
                    <img src="{% static 'images/dictionary.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h3 class="card-title">Dictionary</h3>
                        <p class="card-text">
                            This is a longer card with supporting text
                            below as a natural lead-in to 
                        </p>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-3">
            <a class="card-link text-decoration-none text-dark" href ="{% url 'study_app:flashcards' %}">
                <div class="card mt-4">
                    <img src="{% static 'images/flashcard.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h3 class="card-title">Flash Card</h3>
                        <p class="card-text">
                            This is a longer card with supporting text
                            below as a natural lead-in 
                        </p>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-3">
            <a class="card-link text-decoration-none text-dark" href ="#">
                <div class="card mb-3">
                    <img src="{% static 'images/game.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h3 class="card-title">Game</h3>
                        <p class="card-text">
                            This is a longer card with supporting text
                            below as a natural.with supporting text.
                        </p>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-3">
            <a class="card-link text-decoration-none text-dark" href ="#">
                <div class="card mb-3">
                    <img src="{% static 'images/icon.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h3 class="card-title">Media/Videos</h3>
                        <p class="card-text">
                            This is a longer card with supporting text
                            below as a natural. with supporting text
                        </p>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-3">
            <a class="card-link text-decoration-none text-dark" href ="#">
                <div class="card mb-3">
                    <img src="{% static 'images/wikipedia.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h3 class="card-title">Wikipedia</h3>
                        <p class="card-text">
                            This is a longer card with supporting text
                            below as a natural lead-in to additional
                            content. 
                        </p>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-3">
            <a class="card-link text-decoration-none text-dark" href ="#">
                <div class="card mb-3">
                    <img src="{% static 'images/homework.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h3 class="card-title">Homework</h3>
                        <p class="card-text">
                            This is a longer card with supporting text
                            below as a natural lead-in to additional
                            content. 
                        </p>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>

{% endblock content %}

Cap_Study_App/Study_app/templates/home/homework.html
{% extends 'layout/base.html' %}
{% load static %}



{% block content %}

{% endblock content %}

Cap_Study_App/Study_app/templates/home/projdetail.html
{% extends 'layout/base.html' %} 
{% load static %}


{% block content %}
<div class="container d-flex flex-column align-items-center mb-3">
    <h1>PROJECT INFO</h1>
    <div class="card text-bg-secondary" style="width: 50vw;">
        <div class="card-header">{{project.title}}</div>
        <div class="card-body">
            <p class="card-text">{{project.description}}</p>
            <div class="card-footer bg-transparent">
                Due Date: {{project.due_date}}
                <p>
                    Is finished: {{project.is_finished}}
                </p> 
            </div>
        </div>
    </div>
    <a href="{% url 'study_app:addresources' project.id %}" class="btn btn-success mt-5">Add Resources</a>
      <h3 class="m-4">RESOURCES</h3>
        <div class="d-flex flex-wrap gap-3 justify-content-center mb-4">
          {% for resource in project.resources.all %}
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h4 class="card-title">{{resource.name}}</h4>
                    <h6 class="card-subtitle mb-2">Author: {{resource.author}}</h6>
                    <p class="card-text">
                        Date Published: {{resource.date_published}}
                    </p>
                    <p>
                        Resources Type: {{resource.resources_type}}
                    </p>
                        Price: ${{resource.price}}
                    </p>
                    <a href="{{resource.url}}" class="card-link text-decoration-none">Link</a>
                </div>
            </div>
        
            {% endfor %}
        </div>
</div>

{% endblock content %}

Cap_Study_App/Study_app/templates/home/project.html
{% extends 'layout/base.html' %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <h1 class="text-center mb-0 pt-2 text-light">My Projects</h1>
        {% for project in projects %}

        <div class="col-md-3 pt-5 mb-32">
            <a class="text-decoration-none" href="{% url 'study_app:projdetail' project.id %}">
                <div class="card">
                    <div class="card-header bg-primary text-light">{{project.title}}</div>
                    <div class="card-body text-dark">
                        <p>

                            {{project.description}}
                        </p>
                        </div>
                    <div class="card-body text-dark">{{project.due_date}}</div>
                    <div class="card-body text-dark d-flex">{{project.is_finished}}</div>
                    <div class="card-footer mt-auto"><a href="{% url 'study_app:delete_proj' project.id %}">
                            <i class="bi bi-trash"></i>
                        </a>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
        <br><br>
    </div>
</div>
<br><br>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6 col-lg-4 text-light p-4">

            <form method="POST" class=" d-flex flex-column pt-4" action="{% url 'study_app:projects' %}">
                {% csrf_token %}

                <fieldset class="form-group">
                    <legend class="border-bottom mb-2 mt-1 text-light"><h3>CREATE PROJECT</h3></legend>
                </fieldset>
                {{form}}
                <div class="form-group">
                    <button class="btn btn-success" type="submit">
                        Create
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>


{% endblock content %}

Cap_Study_App/Study_app/templates/home/resource.html
{% extends 'layout/base.html' %} 
{% load static %} 

{% block content %}
<div class="container d-flex justify-content-center">
  <div class="row">
    {% for resource in resources %}

    <div class="col-md-3 pt-5">
      <a class="text-decoration-none"
        href="{% url 'study_app:resourcedetail' project.id %}">
        <div class="card">
          <div class="card-header bg-primary text-dark">{{resource.name}}</div>
          <div class="card-body bg-primary text-dark">{{resource.author}} {{resource.price}} {{resource.resources_type}} {{resource.url}} {{resource.date_published}}
            
          </div>
          
          <div class="card-footer mt-auto">
            <a href="{% url 'study_app:deleteresource' resource.id %}">
              <i class="bi bi-trash"></i>
            </a>
          </div>
        </div>
      </a>
    </div>
    {% endfor %}
    <br /><br />
  </div>
</div>
<br /><br />
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6 col-lg-4">
      <form
        method="POST"
        class="d-flex flex-column"
        action="{% url 'study_app:resource' %}"
      >
        {% csrf_token %}

        <fieldset class="form-group">
          <legend class="border-bottom mb-3 text-center text-light"><h1>RESOURCES</h1></legend>
        </fieldset>
        {{form}}
        <div class="form-group">
          <button class="btn btn-primary mt-4" type="submit">Add</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

Cap_Study_App/Study_app/templates/home/resourcedetail.html
{% extends 'layout/base.html' %}

{% load static %}


{% block content %}
<section class="text-center container">
    <div class="container">
        <div class="content-section p-0 mt-5">
            <div class="m-3">
                <h2>{{resource.name}}</h2>
            </div>
            <hr class="p-0 m-0">
            <div class="author m-5 p-5">{{resource.author}}</div>
            <hr>
            <hr class="p-0 m-0">
            <div class="author m-5 p-5">{{resource.price}}</div>
            <hr>
            <hr class="p-0 m-0">
            <div class="author m-5 p-5">{{resource.resources_type}}</div>
            <hr>
            <hr class="p-0 m-0">
            <div class="author m-5 p-5">{{resource.url}}</div>
            <hr>
            <hr class="p-0 m-0">
            <div class="author m-5 p-5">{{resource.date_published}}</div>
            <hr>
        </div>
    </div>
</section>

{% endblock content %}